# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6512772c4808909cf7eee424e131d69785ea2df927469e45b81d39a06986ce932aa740a55ad3bb91d6a647271b082e82b338ff3be90778e1436e574687a45a50

test:
  secret_key_base: 59483799ae4311f19e1b198701eed4a0321eae73299d7f759e25a5a81f8213265ba5eb1e383321b5fbb51a5bdb8bf1b7a02e9aa9050507d36f3d3807ea1e73e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
